### ISSUE TITLE
Use Mock Services option is not enabled by default

### ISSUE THREAD

**Issue by sughosneo** [dotnet-architecture/eshop-mobile-client#6]
`eShop-mobile-client` is using mock services. So wouldn't this option be selected by default in the `SETTINGS` tab?

![image](https://user-images.githubusercontent.com/13281246/129705121-b2f32165-d978-4b54-bdc4-928c0aa46d70.png)

**Comment by sughosneo** [comment]
@michaelstonis - Could you please review it once? Thank you.

**Comment by michaelstonis** [comment]
@sughosneo this should be the expected functionality. What this is implying is that it will use the _Mock_ or _Sample_ API services and not the fake services in the application. This is the way that the app behaved previously as well. 

If anything, if might make sense to change the wording here because enabling this functionality allows the app to connect to _actual_ APIs. Do you think that may be a better approach here? If not, let me know and I can address it either way.
